arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: localizations.dart
output-class: AppLocalizations
synthetic-package: false
preferred-supported-locales: [en, pl]
untranslated-messages-file: untranslated.json
format: true